include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    sort_constructors_first: true
    prefer_single_quotes: true  
    use_key_in_widget_constructors: true
    prefer_const_constructors: true,
    require_trailing_commas: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_single_class_per_file: true
    prefer_single_widget_per_file: true