import 'package:pet_vet_project/src/features/owner/domain/owner_model.dart';

const ownerList = [
  Owner(
    fullName: 'Alice Johnson',
    ownerId: 101,
    email: 'alice.johnson@example.com',
    phoneNumber: '+1234567890',
    address: '123 Maple Street, Springfield, USA',
  ),
  Owner(
    fullName: 'Bob Smith',
    ownerId: 102,
    email: 'bob.smith@example.com',
    phoneNumber: '+1234567891',
    address: '456 Oak Avenue, Springfield, USA',
  ),
  Owner(
    fullName: 'Catherine Davis',
    ownerId: 103,
    email: 'catherine.davis@example.com',
    phoneNumber: '+1234567892',
    address: '789 Pine Lane, Springfield, USA',
  ),
  Owner(
    fullName: 'David Wilson',
    ownerId: 104,
    email: 'david.wilson@example.com',
    phoneNumber: '+1234567893',
    address: '101 Elm Drive, Springfield, USA',
  ),
  Owner(
    fullName: 'Eva Thompson',
    ownerId: 105,
    email: 'eva.thompson@example.com',
    phoneNumber: '+1234567894',
    address: '202 Cedar Road, Springfield, USA',
  ),
  Owner(
    fullName: 'Frank Miller',
    ownerId: 106,
    email: 'frank.miller@example.com',
    phoneNumber: '+1234567895',
    address: '303 Birch Boulevard, Springfield, USA',
  ),
  Owner(
    fullName: 'Grace Martinez',
    ownerId: 107,
    email: 'grace.martinez@example.com',
    phoneNumber: '+1234567896',
    address: '404 Walnut Way, Springfield, USA',
  ),
  Owner(
    fullName: 'Hannah Lee',
    ownerId: 108,
    email: 'hannah.lee@example.com',
    phoneNumber: '+1234567897',
    address: '505 Cherry Circle, Springfield, USA',
  ),
  Owner(
    fullName: 'Ivy Brown',
    ownerId: 109,
    email: 'ivy.brown@example.com',
    phoneNumber: '+1234567898',
    address: '606 Ash Street, Springfield, USA',
  ),
  Owner(
    fullName: 'Jack White',
    ownerId: 110,
    email: 'jack.white@example.com',
    phoneNumber: '+1234567899',
    address: '707 Willow Avenue, Springfield, USA',
  ),
  Owner(
    fullName: 'Katherine Green',
    ownerId: 111,
    email: 'katherine.green@example.com',
    phoneNumber: '+1234567800',
    address: '808 Fir Lane, Springfield, USA',
  ),
  Owner(
    fullName: 'Liam Harris',
    ownerId: 112,
    email: 'liam.harris@example.com',
    phoneNumber: '+1234567801',
    address: '909 Poplar Drive, Springfield, USA',
  ),
  Owner(
    fullName: 'Mia Robinson',
    ownerId: 113,
    email: 'mia.robinson@example.com',
    phoneNumber: '+1234567802',
    address: '1010 Sycamore Road, Springfield, USA',
  ),
  Owner(
    fullName: 'Noah Walker',
    ownerId: 114,
    email: 'noah.walker@example.com',
    phoneNumber: '+1234567803',
    address: '1111 Hemlock Street, Springfield, USA',
  ),
  Owner(
    fullName: 'Olivia Lewis',
    ownerId: 115,
    email: 'olivia.lewis@example.com',
    phoneNumber: '+1234567804',
    address: '1212 Alder Avenue, Springfield, USA',
  ),
];
