import 'package:pet_vet_project/src/features/pets/domain/pet_model.dart';

List<Pet> pets = [
  Pet(
    petName: 'Whiskers',
    petId: 1,
    ownerId: 101,
    ownerFullName: 'Alice Johnson',
    birthday: DateTime(2020, 5, 15),
    type: PetType.cat,
  ),
  Pet(
    petName: 'Buddy',
    petId: 2,
    ownerId: 102,
    ownerFullName: 'Bob Smith',
    birthday: DateTime(2019, 3, 22),
    type: PetType.dog,
  ),
  Pet(
    petName: 'Shadow',
    petId: 3,
    ownerId: 103,
    ownerFullName: 'Catherine Davis',
    birthday: DateTime(2018, 8, 30),
    type: PetType.cat,
  ),
  Pet(
    petName: 'Max',
    petId: 4,
    ownerId: 104,
    ownerFullName: 'David Wilson',
    birthday: DateTime(2017, 12, 11),
    type: PetType.dog,
  ),
  Pet(
    petName: 'Mittens',
    petId: 5,
    ownerId: 105,
    ownerFullName: 'Eva Thompson',
    birthday: DateTime(2021, 2, 14),
    type: PetType.cat,
  ),
  Pet(
    petName: 'Rocky',
    petId: 6,
    ownerId: 106,
    ownerFullName: 'Frank Miller',
    birthday: DateTime(2020, 7, 25),
    type: PetType.dog,
  ),
  Pet(
    petName: 'Simba',
    petId: 7,
    ownerId: 107,
    ownerFullName: 'Grace Martinez',
    birthday: DateTime(2019, 4, 10),
    type: PetType.cat,
  ),
  Pet(
    petName: 'Charlie',
    petId: 8,
    ownerId: 108,
    ownerFullName: 'Hannah Lee',
    birthday: DateTime(2018, 6, 18),
    type: PetType.dog,
  ),
  Pet(
    petName: 'Luna',
    petId: 9,
    ownerId: 109,
    ownerFullName: 'Ivy Brown',
    birthday: DateTime(2017, 11, 4),
    type: PetType.cat,
  ),
  Pet(
    petName: 'Zeus',
    petId: 10,
    ownerId: 110,
    ownerFullName: 'Jack White',
    birthday: DateTime(2020, 9, 21),
    type: PetType.dog,
  ),
  Pet(
    petName: 'Cleo',
    petId: 11,
    ownerId: 111,
    ownerFullName: 'Katherine Green',
    birthday: DateTime(2019, 1, 5),
    type: PetType.cat,
  ),
  Pet(
    petName: 'Duke',
    petId: 12,
    ownerId: 112,
    ownerFullName: 'Liam Harris',
    birthday: DateTime(2018, 10, 29),
    type: PetType.dog,
  ),
  Pet(
    petName: 'Nala',
    petId: 13,
    ownerId: 113,
    ownerFullName: 'Mia Robinson',
    birthday: DateTime(2021, 3, 15),
    type: PetType.cat,
  ),
  Pet(
    petName: 'Bella',
    petId: 14,
    ownerId: 114,
    ownerFullName: 'Noah Walker',
    birthday: DateTime(2020, 5, 7),
    type: PetType.dog,
  ),
  Pet(
    petName: 'Ginger',
    petId: 15,
    ownerId: 115,
    ownerFullName: 'Olivia Lewis',
    birthday: DateTime(2019, 8, 13),
    type: PetType.cat,
  ),
];
