import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:pet_vet_project/src/common_widgets/custom_button.dart';
import 'package:pet_vet_project/src/common_widgets/date_picker.dart';
import 'package:pet_vet_project/src/core/helper/date_formatter.dart';
import 'package:pet_vet_project/src/core/helper/gaps.dart';
import 'package:pet_vet_project/src/core/helper/validator.dart';
import 'package:pet_vet_project/src/core/style/custom_text_styles.dart';
import 'package:pet_vet_project/src/features/pets/domain/pet_model.dart';
import 'package:pet_vet_project/src/features/pets/presentation/pets_controller.dart';
import 'package:pet_vet_project/src/features/pets/presentation/widgets/add_ped_dialog_dropdown.dart';
import 'package:pet_vet_project/src/features/pets/presentation/widgets/add_pet_dialog_textfield.dart';
import 'package:uuid/uuid.dart';

Future<void> showAddPetDialod({required BuildContext context}) async {
  return showDialog(
    context: context,
    builder: (context) {
      return Dialog(
        child: SingleChildScrollView(
          child: Container(
            child: Padding(
              padding: const EdgeInsets.all(8.0),
              child: _AddPetDialogContent(),
            ),
          ),
        ),
      );
    },
  );
}

class _AddPetDialogContent extends ConsumerStatefulWidget {
  const _AddPetDialogContent();

  @override
  ConsumerState<_AddPetDialogContent> createState() =>
      _AddPetDialogContentState();
}

class _AddPetDialogContentState extends ConsumerState<_AddPetDialogContent> {
  late final TextEditingController _petNameController;
  late final TextEditingController _petBirthDateController;
  late final TextEditingController _petHistoryController;
  late final TextEditingController _petTypeController;
  late final GlobalKey<FormState> _formKey;

  void initState() {
    super.initState();
    _petNameController = TextEditingController();
    _petBirthDateController = TextEditingController();
    _petHistoryController = TextEditingController();
    _petTypeController = TextEditingController();
    _formKey = GlobalKey<FormState>();
  }

  @override
  void dispose() {
    _petNameController.dispose();
    _petBirthDateController.dispose();
    _petHistoryController.dispose();
    _petTypeController.dispose();
    super.dispose();
  }

  _submitForm() async {
    if (_formKey.currentState!.validate()) {
      final dateFormatter = ref.watch(dateFormatterProvider);
      final dateParser = ref.read(dateParserProvider);
      final pet = Pet(
        //FIXME: After adding the FireStore this will be autogenerated, for now we will use Uuid to generate a random id
        petId: Uuid().v4(),
        petName: _petNameController.text,
        type: PetType.fromString(_petTypeController.text),
        birthday: dateParser(_petBirthDateController.text, dateFormatter),
        petHistory: _petHistoryController.text,
      );
      final succes =
          await ref.read(petsControllerProvider.notifier).addPet(pet);
      if (succes) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(
              tr('pet_was_added'),
              style: AppTextStyles(context).s14w400beige,
            ),
            duration: Duration(milliseconds: 500),
          ),
        );
        context.pop();
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final controller = ref.watch(petsControllerProvider);
    final controllerState = controller.isLoading;
    ;
    final dateFormatter = ref.watch(dateFormatterProvider);

    final width = MediaQuery.of(context).size.width * 0.45;
    return Form(
      key: _formKey,
      child: SizedBox(
        width: width,
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Text(tr('add_pet'), style: AppTextStyles(context).s24w400black),
            gapH20,
            AddPetDialogTextField(
              validator: EmptyTextFieldValidator.validate,
              hintText: tr('pet_name'),
              controller: _petNameController,
            ),
            AddPetTypeDialogDropdown(
              controller: _petTypeController,
            ),
            AddPetDialogTextField(
              validator: EmptyTextFieldValidator.validate,
              controller: _petBirthDateController,
              hintText: tr('birth_date'),
              readOnly: true,
              onTap: () async {
                DateTime? selectedDate = await selectDate(context);
                if (selectedDate != null) {
                  _petBirthDateController.text =
                      dateFormatter.format(selectedDate);
                }
              },
            ),
            AddPetDialogTextField(
              validator: EmptyTextFieldValidator.validate,
              hintText: tr('info'),
              controller: _petHistoryController,
            ),
            gapH4,
            CustomElevatedButton(
              onPressed: _submitForm,
              text: tr('add_pet'),
              isLoading: controllerState,
            ),
          ],
        ),
      ),
    );
  }
}
